import React from "react";
import IndividualDisease from "./IndividualDisease";
export default function LateBlight() {
  const post = {
    heading: "Late Blight",
    subheading1: "What is late blight?",
    content1:
      "Late blight is a destructive disease of tomatoes and potatoes that can kill mature plants, and make tomato fruits and potato tubers inedible.  This disease also affects, although typically to a lesser extent, eggplants and peppers, as well as related weeds such as nightshade.  Historically, late blight was responsible for the Irish potato famine, which led to the death of at least one million Irish, and the emigration of another one million Irish to Great Britain, the United States, Australia, Canada and other countries.  More recently, the disease caused severe losses for fresh market tomato producers and home gardeners in Wisconsin.",
    subheading2: "What does late blight look like?",
    content2:
      "On leaves of tomato or potato, late blight begins as pale-green or olive-green areas that quickly enlarge to become brown-black, water-soaked, and oily-looking.  Stems can also exhibit dark-brown to black areas.  If weather conditions are cool and wet, entire plants can collapse and die from late blight in seven to 10 days.  Tomato fruits with late blight develop large, often sunken, golden- to chocolate-brown, firm spots with distinct rings.  Potato tubers with the disease develop a reddish-brown discoloration under the skin and these areas may become sunken.  Affected leaf, stem, fruit or tuber tissue often eventually develops a white-gray, fuzzy look as the late blight organism begins to reproduce.  Other tomato and potato diseases such as Septoria leaf spot (see University of Wisconsin Garden Facts XHT1073), early blight (see University of Wisconsin Garden Facts XHT1074) and Verticillium wilt may be misidentified as late blight.",
    subheading3: "Where does late blight come from?",
    content3:
      "Late blight is caused by the fungus-like water mold Phytophthora infestans.  There are several variants of this organism.  Some variants cause more severe problems on tomatoes; others are more of a problem on potatoes.  P. infestans can be introduced when sporangia (i.e., spore-like structures) of the organism are blown into an area on prevailing winds.  P. infestans can also be introduced on infected plants (e.g., tomato seedlings) or potato tubers that are brought into an area for sale.  P. infestans is unlikely to survive over the winter in Wisconsin soils.  However, the organism can survive on infected plant material that remains alive through the winter.  Such plant materials can include P. infestans-infected tomato plants or fruits kept warm in compost piles, and P. infestans infected potato tubers that have remained in the soil after harvest or have been stored in a warm place.",
    subheading4:
      "How do I save plants with bacterial spot?How do I save a plant with late blight? ",
    content4:
      "Plants showing symptoms of late blight cannot be saved and should be disposed of immediately to limit spread of P. infestans to other plants.  For home gardeners, the preferred method of disposal is to pull affected plants (roots and all), and place them in plastic bags.  The bags should be left in the sun for a few days to make sure that plants, as well as any P. infestans, are totally killed.  Bagged plants then can be put out for trash pickup.  Diseased plants or plant parts (e.g., tomato fruits or potato tubers) should NOT be composted.  Healthy-looking fruits from late-blight-affected tomato plants are safe to eat or preserve.  However, before attempting to preserve any fruit or vegetable, contact your county UW-Extension office for the most current food preservation instructions.  Once tomato fruits or potato tubers begin to show symptoms of late blight, they should NOT be eaten, nor should they be canned or otherwise preserved.",
    subheading5: "How do I avoid problems with late blight in the future?",
    content5:
      "In the spring, dispose of any volunteer tomato and potato plants (as well as weeds such as nightshade) as described above.  All of these plants are potential sources of P. infestans.  For the same reason, DO NOT use tubers from a previous year’s potato crop as seed potatoes.  Instead purchase certified seed potatoes from a reputable supplier each year.  Also, consider planting tomato varieties with late blight resistance.  Such varieties include ‘Better Boy’, ‘Golden Sweet’, ‘Green Zebra’, ‘Juliet’, ‘Legend’, ‘Magic Mountain’, ‘Matt’s Wild Cherry’, ‘Pruden’s Purple’, ‘Regal Plum’, ‘Roma’, ‘Slava’, ‘Stupice’, ‘Sun Sugar’, ‘Wapsipinicon’, and ‘Wisconsin 55’.  The performance of these varieties may vary depending on the variant of P. infestans that is present in a particular growing season, and depending on the weather conditions.  However, ‘Magic Mountain’ and ‘Regal Plum’ have shown excellent resistance to many variants of the late blight organism under a wide range of environmental conditions.",
  };
  return <IndividualDisease post={post} />;
}
